-- NaturalBeauty settings migrations 054-074 consolidated for one-time live deployment.
-- Run this file against the application's database after the base migrations.
START TRANSACTION;

INSERT IGNORE INTO store_settings (setting_group, setting_key, value_json, is_public)
VALUES
  ('trust', 'item_1_title', '"Thoughtful formulas"', 1),
  ('trust', 'item_1_text', '"Made for everyday skin rituals"', 1),
  ('trust', 'item_2_title', '"Skin-first care"', 1),
  ('trust', 'item_2_text', '"Solutions organized around your needs"', 1),
  ('trust', 'item_3_title', '"Secure checkout"', 1),
  ('trust', 'item_3_text', '"Protected and straightforward"', 1),
  ('trust', 'item_4_title', '"Complimentary shipping"', 1),
  ('trust', 'item_4_text', '"On orders above ₹999"', 1),
  ('homepage', 'category_eyebrow', '"Explore the collection"', 1),
  ('homepage', 'category_title', '"Shop by product group."', 1),
  ('homepage', 'category_description', '"Browse products by the way you like to shop."', 1),
  ('homepage', 'category_link_label', '"Explore all groups"', 1),
  ('homepage', 'category_link_url', '"/shop"', 1),
  ('homepage', 'featured_eyebrow', '"Most loved"', 1),
  ('homepage', 'featured_title', '"The best of Natural Beauty"', 1),
  ('homepage', 'featured_description', '"Customer favourites selected from the full collection."', 1),
  ('homepage', 'featured_link_label', '"View all products"', 1),
  ('homepage', 'featured_link_url', '"/shop"', 1),
  ('homepage', 'groups_eyebrow', '"Find your fit"', 1),
  ('homepage', 'groups_title', '"Shop By Categories"', 1),
  ('homepage', 'groups_description', '"Explore products grouped around the needs and preferences that matter to you."', 1),
  ('homepage', 'groups_link_label', '"Explore all groups"', 1),
  ('homepage', 'groups_link_url', '"/shop"', 1),
  ('homepage', 'brand_eyebrow', '"Our philosophy"', 1),
  ('homepage', 'brand_title', '"Nature, refined by thoughtful formulation."', 1),
  ('homepage', 'brand_description', '"We believe products should feel considered, uncomplicated and personal."', 1),
  ('homepage', 'brand_link_label', '"Discover our story"', 1),
  ('homepage', 'brand_link_url', '"/about"', 1),
  ('homepage', 'ingredients_eyebrow', '"Details with intention"', 1),
  ('homepage', 'ingredients_title', '"Details that make a difference."', 1),
  ('homepage', 'ingredients_description', '"Explore the qualities and benefits behind each product."', 1),
  ('homepage', 'principles_title', '"Principles"', 1),
  ('homepage', 'ritual_eyebrow', '"The daily ritual"', 1),
  ('homepage', 'ritual_title', JSON_QUOTE('Small rituals.\nBeautiful consistency.'), 1),
  ('homepage', 'ritual_description', '"Build a simple routine for morning, evening and everything in between."', 1),
  ('homepage', 'ritual_link_label', '"Build your routine"', 1),
  ('homepage', 'ritual_link_url', '"/shop"', 1),
  ('homepage', 'ritual_image_url', '"local:hero"', 1),
  ('homepage', 'ritual_image_alt', '"A calm botanical skincare ritual arranged on stone"', 1),
  ('homepage', 'new_eyebrow', '"Just in"', 1),
  ('homepage', 'new_title', '"New to the ritual"', 1),
  ('homepage', 'new_description', '"Fresh additions designed to find an easy place in your everyday routine."', 1),
  ('homepage', 'new_link_label', '"Shop new arrivals"', 1),
  ('homepage', 'new_link_url', '"/new-arrivals"', 1),
  ('homepage', 'routine_eyebrow', '"Find your routine"', 1),
  ('homepage', 'routine_title', JSON_QUOTE('Your products.\nYour preferences.\nYour choice.'), 1),
  ('homepage', 'routine_description', '"Start with what you need today and discover products that fit naturally into your routine."', 1),
  ('homepage', 'routine_step_1', '"Choose a product group"', 1),
  ('homepage', 'routine_step_2', '"Choose your preference"', 1),
  ('homepage', 'routine_step_3', '"Discover your selection"', 1),
  ('homepage', 'routine_link_label', '"Explore products"', 1),
  ('homepage', 'routine_link_url', '"/shop"', 1),
  ('homepage', 'routine_secondary_label', '"Shop all products"', 1),
  ('homepage', 'routine_secondary_url', '"/shop"', 1),
  ('homepage', 'routine_image_url', '"local:hero"', 1),
  ('homepage', 'routine_image_alt', '"Unbranded products arranged on natural stone"', 1),
  ('homepage', 'testimonials_eyebrow', '"Notes from the ritual"', 1),
  ('homepage', 'testimonial_1_name', '"Aanya Mehta"', 1),
  ('homepage', 'testimonial_1_product', '"Barrier Restore Moisturizer"', 1),
  ('homepage', 'testimonial_1_quote', '"The Barrier Restore Moisturizer became the easiest part of my evening routine. The texture feels rich without feeling heavy."', 1),
  ('homepage', 'testimonial_2_name', '"Riya Kapoor"', 1),
  ('homepage', 'testimonial_2_product', '"Vitamin C Radiance Serum"', 1),
  ('homepage', 'testimonial_2_quote', '"I love how simple the routine feels. The Vitamin C serum layers beautifully under sunscreen in the morning."', 1),
  ('homepage', 'testimonial_3_name', '"Meera Sharma"', 1),
  ('homepage', 'testimonial_3_product', '"Gentle Barrier Cleanser"', 1),
  ('homepage', 'testimonial_3_quote', '"The cleanser and moisturizer combination feels gentle and uncomplicated, which is exactly what I wanted from my routine."', 1),
  ('homepage', 'testimonial_4_name', '"Sara Khan"', 1),
  ('homepage', 'testimonial_4_product', '"Niacinamide Balance Serum"', 1),
  ('homepage', 'testimonial_4_quote', '"The website made it surprisingly easy to browse by concern instead of guessing which product I should start with."', 1),
  ('homepage', 'newsletter_eyebrow', '"The Natural Beauty note"', 1),
  ('homepage', 'newsletter_title', JSON_QUOTE('A little more care,\ndelivered to your inbox.'), 1),
  ('homepage', 'newsletter_description', '"New formulas, thoughtful skincare notes, early access and occasional offers — without the noise."', 1),
  ('homepage', 'newsletter_label', '"Your email address"', 1),
  ('homepage', 'newsletter_placeholder', '"Your email address"', 1),
  ('homepage', 'newsletter_button_label', '"Join the list"', 1),
  ('homepage', 'newsletter_submitting_label', '"Joining…"', 1),
  ('homepage', 'newsletter_privacy', '"By subscribing, you agree to receive Natural Beauty updates. You can unsubscribe at any time."', 1),
  ('homepage', 'newsletter_success', '"You’re on the list. Welcome to the Natural Beauty note."', 1),
  ('homepage', 'brand_image_url', '"local:hero"', 1),
  ('homepage', 'brand_image_alt', '"Botanical skincare bottles in soft natural light"', 1),
  ('homepage', 'brand_note_title', '"Formulated with purpose"', 1),
  ('homepage', 'brand_note_text', '"Designed around skin needs, texture and everyday usability."', 1),
  ('homepage', 'ingredients_image_url', '"local:hero"', 1),
  ('homepage', 'ingredients_image_alt', '"Products and materials arranged for a considered routine"', 1),
  ('homepage', 'highlight_1_title', '"Vitamin C"', 1),
  ('homepage', 'highlight_1_text', '"For brighter-looking, more radiant skin"', 1),
  ('homepage', 'highlight_2_title', '"Niacinamide"', 1),
  ('homepage', 'highlight_2_text', '"Supports balance and smoother-looking texture"', 1),
  ('homepage', 'highlight_3_title', '"Hyaluronic Acid"', 1),
  ('homepage', 'highlight_3_text', '"Helps maintain skin hydration"', 1),
  ('homepage', 'highlight_4_title', '"Ceramides"', 1),
  ('homepage', 'highlight_4_text', '"Supports the skin''s moisture barrier"', 1),
  ('homepage', 'highlight_5_title', '"Salicylic Acid"', 1),
  ('homepage', 'highlight_5_text', '"Helps clarify congested-looking skin"', 1),
  ('homepage', 'highlight_6_title', '"Retinol"', 1),
  ('homepage', 'highlight_6_text', '"Supports smoother, renewed-looking skin"', 1),
  ('homepage', 'principle_1_title', '"Purposeful formulas"', 1),
  ('homepage', 'principle_1_text', '"Every product starts with a clear role in your routine."', 1),
  ('homepage', 'principle_2_title', '"Routine-first design"', 1),
  ('homepage', 'principle_2_text', '"Products made to work naturally within everyday skincare."', 1),
  ('homepage', 'principle_3_title', '"Considered experience"', 1),
  ('homepage', 'principle_3_text', '"Texture, usability and presentation matter as much as the formula story."', 1),
  ('footer', 'twitter_url', '""', 1),
  ('contact', 'phone_secondary', '""', 1),
  ('contact', 'cta_label', '"Explore skincare"', 1),
  ('contact', 'cta_url', '"/shop"', 1),
  ('contact', 'form_eyebrow', '"Customer care"', 1),
  ('contact', 'form_title', '"How can we help?"', 1),
  ('contact', 'form_description', '"Send us a note and our team will get back to you shortly."', 1),
  ('contact', 'name_label', '"Name"', 1),
  ('contact', 'name_placeholder', '"Your name"', 1),
  ('contact', 'email_label', '"Email"', 1),
  ('contact', 'email_placeholder', '"you@example.com"', 1),
  ('contact', 'order_label', '"Order number"', 1),
  ('contact', 'order_optional_label', '"(optional)"', 1),
  ('contact', 'order_placeholder', '"NB-2026-0000"', 1),
  ('contact', 'message_label', '"Message"', 1),
  ('contact', 'message_placeholder', '"How can we help?"', 1),
  ('contact', 'submit_label', '"Send message"', 1),
  ('contact', 'submitting_label', '"Sending…"', 1),
  ('contact', 'sent_label', '"Message sent"', 1),
  ('contact', 'map_title', '"Store location"', 1);

UPDATE store_settings
SET value_json = '5'
WHERE setting_group = 'homepage_limits'
  AND setting_key = 'category_highlights_desktop';

COMMIT;
