ALTER TABLE inventory_movements ADD COLUMN reserved_before INT UNSIGNED NULL, ADD COLUMN reserved_after INT UNSIGNED NULL;
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_number VARCHAR(40) NOT NULL, idempotency_key CHAR(36) NOT NULL, request_fingerprint CHAR(64) NOT NULL,
 customer_id BIGINT UNSIGNED NULL, customer_email VARCHAR(255) NOT NULL, customer_phone VARCHAR(20) NOT NULL, status ENUM('pending','confirmed','processing','shipped','delivered','cancelled') NOT NULL DEFAULT 'confirmed', payment_method ENUM('cod','online') NOT NULL, payment_status ENUM('pending','paid','failed','refunded','partially_refunded') NOT NULL DEFAULT 'pending', currency CHAR(3) NOT NULL DEFAULT 'INR', items_subtotal DECIMAL(12,2) NOT NULL, mrp_total DECIMAL(12,2) NOT NULL, product_discount DECIMAL(12,2) NOT NULL, coupon_discount DECIMAL(12,2) NOT NULL, shipping_amount DECIMAL(12,2) NOT NULL, gift_card_amount DECIMAL(12,2) NOT NULL, grand_total DECIMAL(12,2) NOT NULL, coupon_code VARCHAR(50) NULL, shipping_method_code VARCHAR(30) NOT NULL, shipping_method_name VARCHAR(100) NOT NULL, shipping_estimated_days_min TINYINT UNSIGNED NULL, shipping_estimated_days_max TINYINT UNSIGNED NULL, customer_note VARCHAR(500) NULL, placed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, cancelled_at TIMESTAMP NULL,
 PRIMARY KEY(id), UNIQUE KEY uq_orders_number(order_number), UNIQUE KEY uq_orders_idempotency(idempotency_key), KEY idx_orders_customer(customer_id), CONSTRAINT fk_orders_customer FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NULL, sku_id BIGINT UNSIGNED NULL, sku_code VARCHAR(150) NOT NULL, product_name VARCHAR(255) NOT NULL, product_slug VARCHAR(255) NOT NULL, variant_title VARCHAR(255) NULL, attributes_json JSON NULL, image_path VARCHAR(500) NULL, quantity INT UNSIGNED NOT NULL, unit_price DECIMAL(12,2) NOT NULL, unit_mrp DECIMAL(12,2) NOT NULL, line_subtotal DECIMAL(12,2) NOT NULL, line_mrp_total DECIMAL(12,2) NOT NULL, line_product_discount DECIMAL(12,2) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY idx_order_items_order(order_id), CONSTRAINT fk_order_items_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE, CONSTRAINT fk_order_items_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL, CONSTRAINT fk_order_items_sku FOREIGN KEY(sku_id) REFERENCES product_skus(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS order_addresses (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, address_type VARCHAR(20) NOT NULL DEFAULT 'shipping', first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL, address_line_1 VARCHAR(255) NOT NULL, address_line_2 VARCHAR(255) NULL, landmark VARCHAR(255) NULL, city VARCHAR(100) NOT NULL, state VARCHAR(100) NOT NULL, postal_code VARCHAR(20) NOT NULL, country_code CHAR(2) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), UNIQUE KEY uq_order_address(order_id,address_type), CONSTRAINT fk_order_addresses_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS order_status_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL, note VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), KEY idx_order_history(order_id,created_at), CONSTRAINT fk_order_history_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
