ALTER TABLE orders ADD COLUMN payment_expires_at TIMESTAMP NULL;
CREATE TABLE IF NOT EXISTS payments (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, order_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(30) NOT NULL, payment_method VARCHAR(30) NOT NULL, provider_order_id VARCHAR(100) NULL, provider_payment_id VARCHAR(100) NULL, amount DECIMAL(12,2) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'INR', status ENUM('created','authorized','captured','failed','cancelled') NOT NULL DEFAULT 'created', failure_code VARCHAR(100) NULL, failure_description VARCHAR(255) NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, authorized_at TIMESTAMP NULL, captured_at TIMESTAMP NULL, failed_at TIMESTAMP NULL, PRIMARY KEY(id), UNIQUE KEY uq_payment_provider_order(provider,provider_order_id), UNIQUE KEY uq_payment_provider_payment(provider,provider_payment_id), KEY idx_payments_order(order_id), CONSTRAINT fk_payments_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS payment_events (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, provider VARCHAR(30) NOT NULL, provider_event_id VARCHAR(150) NULL, event_type VARCHAR(100) NOT NULL, payload_hash CHAR(64) NOT NULL, payload_json JSON NOT NULL, processing_status ENUM('received','processed','ignored','failed') NOT NULL DEFAULT 'received', received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at TIMESTAMP NULL, error_message VARCHAR(255) NULL, PRIMARY KEY(id), UNIQUE KEY uq_payment_event(provider,provider_event_id), KEY idx_payment_event_hash(payload_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS gift_card_holds (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, gift_card_id BIGINT UNSIGNED NOT NULL, order_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(12,2) NOT NULL, status ENUM('active','consumed','released') NOT NULL DEFAULT 'active', expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, released_at TIMESTAMP NULL, consumed_at TIMESTAMP NULL, PRIMARY KEY(id), UNIQUE KEY uq_gift_hold_order(order_id), KEY idx_gift_hold_card(gift_card_id,status), CONSTRAINT fk_gift_hold_card FOREIGN KEY(gift_card_id) REFERENCES gift_cards(id) ON DELETE CASCADE, CONSTRAINT fk_gift_hold_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
